/*Create DB to be used*/
CREATE DATABASE happiness_data;

/*Create table structure*/
CREATE TABLE happiness_data.happiness_by_region_yr
	(UNIQUE_ID VARCHAR(40),
    YEAR INT,
    COUNTRY VARCHAR(30),
    REGION VARCHAR(30),
    CONTINENT VARCHAR(30),
    HAPPINESS_RANK INT,
	HAPPINESS_SCORE FLOAT,
	ECONOMY_GDP_PER_CAPITA FLOAT,
	FAMILY FLOAT,
	HEALTH_LIFE_EXPECTANCY FLOAT,
	FREEDOM FLOAT,
	GENEROSITY FLOAT,
	TRUST_GOVERNMENT_CORRUPTION FLOAT,
	DYSTOPIA_RESIDUAL FLOAT,
    PRIMARY KEY (UNIQUE_ID));
    
/*Convert Scores into ranks, deciles, quartiles for ease of analysis*/
create table happiness_data.happiness_by_region_yr_all as
select UNIQUE_ID,
		YEAR,
		COUNTRY,
		REGION,
		CONTINENT,
		HAPPINESS_SCORE,
		HAPPINESS_RANK,
		ntile(10) OVER(PARTITION BY year ORDER BY HAPPINESS_RANK) AS HAPPINESS_RANK_DECILE,
        ntile(4) OVER(PARTITION BY year ORDER BY HAPPINESS_RANK) AS HAPPINESS_RANK_QUARTILE,
		ECONOMY_GDP_PER_CAPITA as ECONOMY_GDP_PER_CAPITA_SCORE,
        ECONOMY_GDP_PER_CAPITA_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY ECONOMY_GDP_PER_CAPITA_RANK) AS ECONOMY_GDP_PER_CAPITA_RANK_DECILE,
		ntile(4) OVER(PARTITION BY year ORDER BY ECONOMY_GDP_PER_CAPITA_RANK) AS ECONOMY_GDP_PER_CAPITA_RANK_QUARTILE,
        (ECONOMY_GDP_PER_CAPITA/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS ECONOMY_GDP_PER_CAPITA_PCT,
        FAMILY as FAMILY_SCORE,
        FAMILY_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY FAMILY_RANK) AS FAMILY_RANK_DECILE,
		ntile(4) OVER(PARTITION BY year ORDER BY FAMILY_RANK) AS FAMILY_RANK_QUARTILE,
        (FAMILY/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS FAMILY_PCT,
		HEALTH_LIFE_EXPECTANCY as HEALTH_LIFE_EXPECTANCY_SCORE,
        HEALTH_LIFE_EXPECTANCY_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY HEALTH_LIFE_EXPECTANCY_RANK) AS HEALTH_LIFE_EXPECTANCY_RANK_DECILE,
		ntile(4) OVER(PARTITION BY year ORDER BY HEALTH_LIFE_EXPECTANCY_RANK) AS HEALTH_LIFE_EXPECTANCY_RANK_QUARTILE,
        (HEALTH_LIFE_EXPECTANCY/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS HEALTH_LIFE_EXPECTANCY_PCT,
		FREEDOM as FREEDOM_SCORE,
        FREEDOM_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY FREEDOM_RANK) AS FREEDOM_RANK_DECILE,
		ntile(4) OVER(PARTITION BY year ORDER BY FREEDOM_RANK) AS FREEDOM_RANK_QUARTILE,
        (FREEDOM/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS FREEDOM_PCT,
		GENEROSITY as GENEROSITY_SCORE,
        GENEROSITY_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY GENEROSITY_RANK) AS GENEROSITY_RANK_DECILE,
		ntile(4) OVER(PARTITION BY year ORDER BY GENEROSITY_RANK) AS GENEROSITY_RANK_QUARTILE,
        (GENEROSITY/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS GENEROSITY_PCT,
		TRUST_GOVERNMENT_CORRUPTION as TRUST_GOVERNMENT_CORRUPTION_SCORE,
        TRUST_GOVERNMENT_CORRUPTION_RANK,
        ntile(10) OVER(PARTITION BY year ORDER BY TRUST_GOVERNMENT_CORRUPTION_RANK) AS TRUST_GOVERNMENT_CORRUPTION_RANK_DECILE,
        ntile(4) OVER(PARTITION BY year ORDER BY TRUST_GOVERNMENT_CORRUPTION_RANK) AS TRUST_GOVERNMENT_CORRUPTION_RANK_QUARTILE,
        (TRUST_GOVERNMENT_CORRUPTION/(HAPPINESS_SCORE-DYSTOPIA_RESIDUAL)) AS TRUST_GOVERNMENT_CORRUPTION_PCT
from 
	(select *,
			ntile(157) OVER(PARTITION BY year ORDER BY ECONOMY_GDP_PER_CAPITA desc) AS ECONOMY_GDP_PER_CAPITA_RANK,
			ntile(157) OVER(PARTITION BY year ORDER BY FAMILY desc) AS FAMILY_RANK,
			ntile(157) OVER(PARTITION BY year ORDER BY HEALTH_LIFE_EXPECTANCY desc) AS HEALTH_LIFE_EXPECTANCY_RANK,
			ntile(157) OVER(PARTITION BY year ORDER BY FREEDOM desc) AS FREEDOM_RANK,
			ntile(157) OVER(PARTITION BY year ORDER BY GENEROSITY desc) AS GENEROSITY_RANK,
			ntile(157) OVER(PARTITION BY year ORDER BY TRUST_GOVERNMENT_CORRUPTION desc) AS TRUST_GOVERNMENT_CORRUPTION_RANK
	from happiness_data.happiness_by_region_yr) a;
    
    
    


