CREATE DATABASE happiness_data;

CREATE TABLE happiness_data.happiness_by_region_yr
	(UNIQUE_ID VARCHAR(40),
    YEAR INT,
    COUNTRY VARCHAR(30),
    REGION VARCHAR(30),
    CONTINENT VARCHAR(30),
    HAPPINESS_RANK INT,
	HAPPINESS_SCORE FLOAT,
	ECONOMY_GDP_PER_CAPITA FLOAT,
	FAMILY FLOAT,
	HEALTH_LIFE_EXPECTANCY FLOAT,
	FREEDOM FLOAT,
	GENEROSITY FLOAT,
	TRUST_GOVERNMENT_CORRUPTION FLOAT,
	DYSTOPIA_RESIDUAL FLOAT,
    PRIMARY KEY (UNIQUE_ID));
